version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: community
    volumes:
      - mongodb_community:/data/db

volumes:
  mongodb_community: