server:
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: community
      auto-index-creation: true

security:
  auth:
    secret: amadeu
